version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: saas-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - saas-network

  redis:
    image: redis:7-alpine
    container_name: saas-redis
    ports:
      - "6379:6379"
    networks:
      - saas-network

volumes:
  mongodb_data:

networks:
  saas-network:
    driver: bridge
