global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'express-api'
    static_configs:
      - targets: ['express-api:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nextjs-frontend'
    static_configs:
      - targets: ['nextjs-frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
