version: '3'
services:
  acapy-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1
    ports:
      - "3000:3000"
      - "3001:3001"
    command: >
      start
      --inbound-transport http 0.0.0.0 3000
      --outbound-transport http
      --admin 0.0.0.0 3001
      --endpoint http://localhost:3000
      --label "ACA-Py Agent"
      --wallet-type indy
      --wallet-name demo-wallet
      --wallet-key demo-key
      --auto-provision
      --auto-accept-invites
      --auto-accept-requests
      --genesis-url https://raw.githubusercontent.com/bcgov/von-network/main/genesis.txn
      --log-level info
  mediator:
    image: bcgovimages/aries-cloudagent:py36-1.16-1
    ports:
      - "3002:3002"
      - "3003:3003"
    command: >
      start
      --inbound-transport http 0.0.0.0 3002
      --outbound-transport http
      --admin 0.0.0.0 3003
      --endpoint http://localhost:3002
      --label "Mediator Agent"
      --wallet-type indy
      --wallet-name mediator-wallet
      --wallet-key mediator-key
      --auto-provision
      --mediation
      --log-level info
